### ISSUE TITLE
Error: toth3-overlay's package.json lacks a "nodecg" property, and therefore cannot be parsed.

### ISSUE THREAD

**Issue by AlexRubioRotalde** [TipoftheHats/toth3-overlay#1]
Hello can you fix this error i cant start toth3-overlay
Error: toth3-overlay's package.json lacks a "nodecg" property, and therefore cannot be parsed.
Thanks

**Comment by Lange** [comment]
toth3-overlay is a NodeCG v0.6 bundle. You cannot load it in NodeCG v0.7.

**Comment by AlexRubioRotalde** [comment]
Fixed Thx

2016-04-02 20:24 GMT-05:00 Alex Van Camp notifications@github.com:
